version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: edb

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
